[deploy]
bucket = 'cfn-artifacts-cfelt'
region = 'ca-central-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'CFelt22/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "cfn-artifacts-cfelt"
BuildSpec = 'backend-flask/buildspec.yml'